name: Run E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE_REPO_E2E: my-test

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright:focal  # 使用 Playwright 的 Docker 镜像

    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4  # 更新到 v4
      with:
        node-version: '16'  # 确保使用支持 ES 模块的 Node.js 版本

    - name: Install dependencies
      run: |
        npm install
        npx playwright install

    - name: Run the BDD test
      run: |
        npm run e2e:test
      env:
        HEADLESS: true

    - name: Upload HTML report
      if: always()  # 无论测试是否失败都执行上传报告的步骤
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: reports/report.html  # 替换为实际的 HTML 报告文件路径

    - name: get allure history
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages
        
    - name: generate report
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_result: ../reports/allure-results
        allure_history: allure-history
        allure_report: report
        keep_report: 20
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3  # 使用更新版本的 GitHub Pages 部署操作
      with:
        github_token: ${{ secrets.TEST_TOKEN }}
        publish_branch: gh-pages  # 修改为你的 GitHub Pages 分支
        publish_dir: report  # 指向生成的 Allure 报告目录
